
<script src='<?php echo COMMON; ?>js/validar.js'></script>
<div id="CargaformServicios">
    <!--    <div class="container-fluid card-header bg-lightblue border-success"> 
            <h5 class="text-center "><?php echo $this->accion; ?></h5>
        </div>-->
    
    <form id="form3" method="post" enctype="multipart/form-data" action="<?php echo RUTA_URL . 'ordenes/UPDATEFINALIZARORDEN'; ?>">
        <div class="card-body">
            <input type="hidden" id="txtsosId" name="txtsosId" value="<?php echo $this->datos[0]['Codigo']; ?>">
            <div class="form-group">
                <fieldset>
                    <div class="container-fluid card">
                        <div class="row ">
                            <div class="container-fluid card-header bg-lightblue border-success"> 
                                <h5 class="text-center "><?php echo $this->accion; ?></h5>
                            </div>  </div>

                    </div>
                    <STYLE type="text/css">
                        H4 { text-align: center}
                    </STYLE>
                    <div class="container-fluid card"  >
                        <div class="row alert-success" >
                            <div class="col-12 col-md-12" >
                                <div class="form-row center-block" >
                                    <h4 class="col-12 col-md-12" align='center'>Orden del Servicio: <?php echo $this->datos[0]['Codigo']; ?>  </h4>
                                    <input type="hidden" name="TXTIDSERVICIO" value="<?php
                                    if (empty($this->datos)) {
                                        
                                    } else {
                                        echo $this->datos[0]['Codigo'];
                                    }
                                    ?>">
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="container-fluid card">
                <div class="row ">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Numero de Contrato:  &nbsp;</label>
                            <input type="hidden" id="TXTIDCONTRATO" name="TXTIDCONTRATO" value="<?php echo $this->datos[0]['IdContrato']; ?>">
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo $this->datos[0]['IdContrato']; ?> &nbsp;</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Servicio Contratado:  &nbsp;</label>
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo $this->datos[0]['sosnombre']; ?> &nbsp;</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Valor Mensualidad:  &nbsp;</label>
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <?php
                            $valor = $this->datos[0]['sosValor'];
                            $formato = number_format($valor, 2);
                            ?>
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo '$ ', $formato; ?> &nbsp;</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Fecha de Contrato:  &nbsp;</label>
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo $this->datos[0]['FechaGenerada']; ?> &nbsp;</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid card">
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Numero de documento:  &nbsp;</label>
                            <input type="hidden" name="txtCedula" value="<?php
                            if (empty($this->datos)) {
                                
                            } else {
                                echo $this->datos[0]['uosDocumento'];
                            }
                            ?>">
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo $this->datos[0]['uosDocumento']; ?> &nbsp;</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Nombres y Apellidos:  &nbsp;</label>
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo $this->datos[0]['uosNombres']; ?> <?php
                                echo ' ';
                                echo $this->datos[0]['uosApellidos'];
                                ?> &nbsp;</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Direccion:  &nbsp;</label>
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo ucwords(strtolower($this->datos[0]['uosDireccion'])); ?><?php
                                echo ' - Barrio: ';
                                echo ucwords(strtolower($this->datos[0]['banombre']));
                                ?> &nbsp;</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Telefono:  &nbsp;</label>
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo $this->datos[0]['uosTelefono']; ?>  &nbsp;</label>
                        </div>
                    </div>
                </div>

            </div>
            <div class="container-fluid card">
                <div class="row alert-info">
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Detalle del Prodedimiento:  &nbsp;</label>
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row ">
                            <input type="hidden" id="txtidservicioarealziar" name="txtidservicioarealziar" value="<?php echo $this->datos2[0]['sosId']; ?>">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo $this->datos2[0]['sosNombre']; ?>  &nbsp;</label>
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo $this->datos2[0]['sosDescripcion']; ?>  &nbsp;</label>
                             <input type="hidden" id="txtvalordelservicio" name="txtvalordelservicio" value="<?php echo $this->datos2[0]['sosValor']; ?>">
                            <?php
                            $valor2 = $this->datos2[0]['sosValor'];
                            $formato2 = number_format($valor2, 2);
                            ?>
                            <label for="cliente_numero_documento" class="bmd-label-floating"> <?php echo '$ ', $formato2; ?> &nbsp;</label>


                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid card">
                <br>
                <div class="group">
                    <div class="alert alert-warning" >
                        <label for="exampleInputName">Observaciones </label>
                        <input name="TXTOBSERVACIONSINSTALACION" required class="form-control" value="" id="TXTOBSERVACIONSINSTALACION " type="text" aria-describedby="nameHelp" placeholder="Describa las novedades presentadas al realizar la instalacion del servicio">               
                    </div>
                </div>
            </div>

            <div class="container-fluid card">
                <br>
                <div class="row">
                    <br>
                    <br>
                    <div class="col-12 col-md-4">
                        <div class="form-row">
                            <label for="cliente_numero_documento" class="bmd-label-floating"> Seleccionar Fecha:  &nbsp;</label>
                        </div>
                    </div>
                    <div class="col-12 col-md-8">
                        <div class="form-row">
                            <input name="TXTFECHAINICIOCONTRATO" required class="form-control" value="" id="TXTFECHAINICIOCONTRATO " type="datetime-local" aria-describedby="nameHelp" placeholder="Describa las novedades presentadas al realizar la instalacion del servicio">               

                        </div>
                    </div>
                    <br>
                </div>
            </div>
            </fieldset>
<!--  <button type="submit" class="btn btn-raised btn-info btn-sm"><i class="far fa-save"></i> &nbsp; Guardar</button>-->
        </div>


        <div class="form-group card-footer bg-transparent border-success">
            <div class="form-row">
                <div class="col-md-6">
                    <a class="btn btn-danger btn-block" href="<?php echo RUTA_URL . 'ordenes/ordenes'; ?>">Volver</a>
                </div>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-raised btn-info btn-sm col-md-12"><i class="far fa-save"></i> &nbsp; Guardar</button>
                   
                </div>
            </div>
        </div>
    </form>
</div> 
