<script src='<?php echo COMMON; ?>js/validar.js'></script>
<script src="<?php echo COMMON; ?>/js/ajax.js" type="text/javascript"></script>
<script src="<?php echo COMMON; ?>/js/jquery.js" type="text/javascript"></script>
<script src="<?php echo $_layoutParams['ruta_js']; ?>script.js" type="text/javascript"></script>
<div class="">
    <div id="divcarga">

        <table class="table table-bordered table-hover tab-custom-content table-borderless table-sm " id="dataTable"  >
            <thead>
                <tr> 
                    <th scope="col" >Num-Cto</th>
                    <th scope="col" >Docuemto</th>
                    <th scope="col" >Nombres y Apellidos</th>  
                    <th scope="col" >Direccion</th>
                    <th scope="col" >Servicio Contratado</th>
                    <th scope="col" >Tipo de Orden</th>
                    <th scope="col" >Fecha de Orden</th>

                    <th scope="col" >Opciones</th>   
                </tr>
            </thead>
            <tbody class="table-condensed ">
                <?php for ($A = 0; $A < count($this->ConsultaOrdenesPrincipal); $A++) { ?>
                    <tr >
                        <td scope="row" ><?php echo ucwords(strtolower($this->ConsultaOrdenesPrincipal[$A]['IdContrato'])); ?></td>
                        <td  ><?php echo ucwords(strtolower($this->ConsultaOrdenesPrincipal[$A]['uosDocumento'])); ?></td>
                        <td  ><?php echo ucwords(strtolower($this->ConsultaOrdenesPrincipal[$A]['uosNombres'])); ?><?php
                            echo ' ';
                            echo ucwords(strtolower($this->ConsultaOrdenesPrincipal[$A]['uosApellidos']));
                            ?></td>
                        <td ><?php echo ucwords(strtolower($this->ConsultaOrdenesPrincipal[$A]['uosDireccion'])); ?><?php
                            echo ' ';
                            echo ucwords(strtolower($this->ConsultaOrdenesPrincipal[$A]['banombre']));
                            ?></td>
                        <?php for ($D = 0; $D < count($this->consulta_servicio_por_contrato); $D++) { ?>
                            <?php if ($this->ConsultaOrdenesPrincipal[$A]['IdContrato'] == $this->consulta_servicio_por_contrato[$D]['cosId']) {
                                ?>
                                <td ><?php echo ucwords(strtolower($this->consulta_servicio_por_contrato[$D]['sosNombre'])); ?></td>
                            <?php }
                            ?>
                        <?php } ?>
                        <td class="alert <?php echo $this->ConsultaOrdenesPrincipal[$A]['orsestilo']; ?>"><?php echo ucwords(strtolower($this->ConsultaOrdenesPrincipal[$A]['orsTipoServicio'])); ?></td>
                        <td ><?php echo ucwords(strtolower($this->ConsultaOrdenesPrincipal[$A]['FechaGenerada'])); ?></td>
                        <td class="form-row ">

                            <?php // echo $this->accion;   ?>



                            <?php
                            $estilo = $this->ConsultaOrdenesPrincipal[$A]['orsestilo'];
                            if ($estilo == 'alert-info') {
                                ?>

                                <?php
                            } else {
                                if ($this->ConsultaOrdenesPrincipal[$A]['orsTipoServicio'] == 'INSTALACION') {
                                    ?>
                                    <button  class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="ACTIVAR CONTRATO"                                    
                                             value="<?php echo $this->ConsultaOrdenesPrincipal[$A]['Codigo']; ?>" 
                                             name="btnInstalcion" 
                                             id="btnInstalcion">
                                        <i class="fa fa-save fa-sm" ></i> INTALAR</button>
                                    <?php
                                }if ($this->ConsultaOrdenesPrincipal[$A]['orsTipoServicio'] == 'RECONEXION') {
                                    ?>
                                    <button  class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="SUSPENDER CONTRATO"                                        
                                             value="<?php echo $this->ConsultaOrdenesPrincipal[$A]['Codigo']; ?>" 
                                             name="btnreconexion" 
                                             id="btnreconexion"><i class="fa fa-plug fa-sm" ></i>  RECONEXION </button>
                                             <?php
                                         } if ($this->ConsultaOrdenesPrincipal[$A]['orsTipoServicio'] == 'DESCONECXIÓN POR MORA') {
                                             ?>

                                    <button  class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="SUSPENDER CONTRATO"                                        
                                             value="<?php echo $this->ConsultaOrdenesPrincipal[$A]['Codigo']; ?>" 
                                             name="btnejecutarordenvarias" 
                                             id="btnejecutarordenvarias">
                                        <i class="fa fa-scissors fa-sm" ></i>  SUSPENDER </button>

                                    <?php
                                } if ($this->ConsultaOrdenesPrincipal[$A]['orsTipoServicio'] == 'DESCONECXIÓN VOLUNTARIA') {
                                    ?>

                                    <button  class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="SUSPENDER CONTRATO"                                        
                                             value="<?php echo $this->ConsultaOrdenesPrincipal[$A]['Codigo']; ?>" 
                                             name="btnejecutarordenvarias" 
                                             id="btnejecutarordenvarias">
                                        <i class="fa fa-scissors fa-sm" ></i>  SUSPENDER </button>

                                    <?php
                                }
                            }
                            ?>
                            <?php
                            if ($estilo == 'alert-danger') {
                                ?>
                                <?php
                            } else {
                                ?>
                                <button  class=" btn btn-info btn-sm" 
                                         title="Novedades" 
                                         value="<?php echo $this->ConsultaOrdenesPrincipal[$A]['Codigo']; ?>" 
                                         name="btnNovedadesOrdenes" 
                                         id="btnNovedadesOrdenes">
                                    <i class="fa fa-bars fa-sm" ></i></button>

                                <?php
                            }
                            ?>



                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
        <style type="text/css" >
            #btnEliminarBarrio{
                width: 25px; height: 25px; border: 0
            }
            #btnEditarBarrio{
                width: 25px; height: 25px; border: 0;
            }

        </style>

        <script>
        $(document).on("click", "#btnInstalcion", function () {
         $('#modalunico2').modal('show');
        cargadivconsulta('contenidomodal2', 'FinalizarOrden/' + $(this).val(), '');

    });
     $(document).on("click", "#btnejecutarordenvarias", function () {
         $('#modalunico2').modal('show');
        cargadivconsulta('contenidomodal2', 'FormFinalizarOrdenesVarias/' + $(this).val(), '');

    });
      $(document).on("click", "#btnNovedadesOrdenes", function () {
         $('#modalunico3').modal('show');
        cargadivconsulta('contenidomodal3', 'Consulta_INSTALACION/' + $(this).val(), '');

    });
     $(document).on("click", "#btnreconexion", function () {
         $('#modalunico2').modal('show');
        cargadivconsulta('contenidomodal2', 'fromreconexion/' + $(this).val(), '');

    });
        </script>
    </div>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" id="modalunico2" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">

        <div class="modal-content">

            <div class="modal-body">

                <div id="contenidomodal2">

                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" id="modalunico3" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">

        <div class="modal-content">

            <div class="modal-body">

                <div id="contenidomodal3">

                </div>
            </div>
        </div>
    </div>
</div>