<div>
    <h1>
        <br>
        <br><!-- comment --> 
    </h1>
</div>
<div class="card card-login mx-auto mt-5 ">
    <div class="card-header text-center">
        <h2>Inicio de Sesion</h2>
    </div>
    <div class="card-body">
        <form method="post" action="<?php echo RUTA_URL . 'inicio/setlogin'; ?>">
            <center>
                <img src="<?php echo COMMON; ?>img/login2.png" style=" width: 250px; height: 120px;" >
            </center>
            <div class="form-group">
                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                <?php if (isset($_COOKIE['user']) && !empty($_COOKIE['user'])) { ?>
                    <input name="txtUsuario" value="<?php echo $_COOKIE['user']; ?>" class="form-control" id="exampleInputEmail1" required type="text" aria-describedby="emailHelp" placeholder="Ingrese usuario o correo">
                <?php } else { ?>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text"><span><i class="fa fa-user"></i></span></div>
                        </div>
                        <input name="txtUsuario" required class="form-control" id="exampleInputEmail1" type="text" aria-describedby="emailHelp" placeholder="Ingrese usuario">
                    </div>


                <?php } ?>
            </div>
            <div class="input-group form-group">

               
                <div class="input-group-prepend">
                    <div class="input-group-text"><span><i class="fa fa-lock"></i></span></div>
                </div>
                <?php if (isset($_COOKIE['pass']) && !empty($_COOKIE['pass'])) { ?>

                    <input name="txtPassword" required value="<?php echo $_COOKIE['pass']; ?>" class="form-control" id="exampleInputPassword1" type="password" placeholder="Ingrese contraseña">

                <?php } else { ?>
                    <input name="txtPassword" required class="form-control" id="exampleInputPassword1" type="password" placeholder="Ingrese contraseña">
                <?php } ?>
            </div>
            <div class="form-group">
                <?php if (isset($_COOKIE['user']) && $_COOKIE['pass']) { ?>
                    <div class="form-check">
                        <label class="form-check-label">
                            <input checked value="A" name="txtRecordarme" class="form-check-input" type="checkbox"> Recordar Contraseña
                        </label>
                    </div>
                <?php } else { ?>
                    <div class="form-check">
                        <label class="form-check-label">
                            <input value="I" name="txtRecordarme" class="form-check-input" type="checkbox"> Recordar Contraseña
                        </label>
                    </div>
                <?php } ?>
            </div>
<!--            <div class="form-group">
                ¡No tienes una cuenta! <a href="<?php echo RUTA_URL . 'inicio/registro'; ?>"> Registrate</a>
            </div>-->
            <input type="submit" value="Login" class="btn btn-primary btn-block">
        </form>
    </div>
</div>