<?php 
ob_start();
?>
<head>
        <meta charset="utf-8">
        <link rel='icon' href='<?php echo COMMON; ?>img/icono.ico'>
    <a href="../common/img/icono.ico"></a>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><?php echo $this->title; ?></title>
    <!--!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" > 
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="<?php echo COMMON; ?>assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo COMMON; ?>assets/dist/css/adminlte.min.css">


    <!-- jQuery -->
    <script src="<?php echo COMMON; ?>assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="<?php echo COMMON; ?>assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="<?php echo COMMON; ?>/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script>
    <link href="<?php echo COMMON; ?>/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo COMMON; ?>/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet" type="text/css"/>
    <script src="<?php echo COMMON; ?>/datatables/extensions/Responsive/js/dataTables.responsive.js" type="text/javascript"></script>
    <link href="<?php echo COMMON ?>/datatables/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" type="text/css"/>
    <script src="<?php echo COMMON; ?>assets/dist/js/adminlte.min.js"></script>
    <script src="<?php echo COMMON; ?>js/jquery.js"></script>
    <link href="<?php echo COMMON; ?>vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo COMMON; ?>vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="<?php echo COMMON; ?>vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="<?php echo COMMON; ?>css/sb-admin.css" rel="stylesheet">
    <link href="<?php echo COMMON; ?>css/pnotify.custom.min.css" rel="stylesheet">
    <link href='<?php echo COMMON; ?>formvalidation/dist/css/bootstrapValidator.css' rel='stylesheet'><script src='<?php echo COMMON; ?>formvalidation/dist/js/bootstrapValidator.js'></script><script src='<?php echo COMMON; ?>formvalidation/dist/js/language/es_CL.js'></script>
</head>
<link href="<?php echo COMMON; ?>/sweetalert.css" rel="stylesheet" type="text/css"/>
<script src="<?php echo COMMON; ?>/sweetalert.min.js" type="text/javascript"></script>
<script src='<?php echo COMMON; ?>js/validar.js'></script>

<script src="<?php echo COMMON; ?>/js/ajax.js" type="text/javascript"></script>
<script src="<?php echo COMMON; ?>/js/jquery.js" type="text/javascript"></script>
<script src='<?php echo COMMON; ?>js/validar.js'></script>
<script src="<?php echo $_layoutParams['ruta_js']; ?>script.js" type="text/javascript"></script>

<div id="cargaSuspender"class="conainer container-fluid">

    <div class="alert alert-success center-block center text-center" role="alert">
        <h4>Reporte Morosos</h4> 
    </div>

    <div class="">
        <table   style="width: 100%; border:1;" class=" table table-bordered table-hover tab-custom-content table-borderless table-sm  table-condensed" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr style="text-align: center;"> 
                    <th style="" class="col-sm-">NIT</th>
                    <th style="" class="col-sm-">NOMBRES & APELLIDOS</th>
                    <th style="" class="col-sm-">DIRECCION</th>
                    <th style="" class="col-sm-">CTO</th>

                    <th style="" class="col-sm-">N/FACT</th>
                    <th style="" class="col-sm-">DEUDA</th>   
                </tr>
            </thead>
            <tbody class="table-condensed">
                <?php
                for ($i = 0; $i < count($this->datos); $i++) {
                    ?>
                    <tr>
                        <td class = "text-center" ><?php echo ucwords(strtolower($this->datos[$i]['uosDocumento'])); ?></td>
                        <td class="text-center"><?php echo ucwords(strtolower($this->datos[$i]['NOMBRES'])); ?></td>
                        <td class="text-center"><?php echo ucwords(strtolower($this->datos[$i]['DIRECCION'])); ?></td>
                   <td class="text-center"><?php echo ucwords(strtolower($this->datos[$i]['froContrato'])); ?></td>
                 
                        <td class="text-center"><?php echo ucwords(strtolower($this->datos[$i]['froNomFctura'])); ?> </td>

                        <?php
                        $valor = $this->datos[$i]['froTotalVenta'];
                        $formato = number_format($valor, 2);
                        ?>
                        <td><?php echo '$ ', $formato; ?></td>
                       
                    </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </div>
</div>
<script>
    $(document).on('click', '#btncortar', function () {
        cargadivconsulta('cargaSuspender', 'corte/' + $(this).val(), '');
    });
//    cargar el modal para el pago de la factura

$(document).on("click", "#btnPagarFactura", function () {
//            swal($(this).val());
$('#modalFagaFactura').modal('show');
cargadivconsulta('contenidomodal3', 'pagarfactura/' + $(this).val(), '');

});
          
</script>
<script>
//    cargar el modal para el pago de la factura

$(document).on("click", "#btnEditarFactura", function () {
//            swal($(this).val());
$('#modalFagaFactura').modal('show');
cargadivconsulta('contenidomodal3', 'Editarfactura/' + $(this).val(), '');

});
          
</script>
<!-- Modal pagar factura -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" id="modalFagaFactura" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">

        <div class="modal-content">

            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div id="contenidomodal3">

                </div>
            </div>
        </div>
    </div>
</div>


<style type="text/css" >

    #btnPagarFactura{
        width: 100px; height: 25px; border: 0;
    }
    #imprimir{
        width: 28px; height: 25px; border: 0;
    }


    #btnEditarFactura{
        width: 28px; height: 25px; border: 0;
    }
</style>


<div class="modal fade" tabindex="-1" id="modalEliminarServicio1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <!--            <div class="modal-header">Mensaje de confirmacion<button class="close" data-dismiss="modal">&times;</button></div>-->
            <div class="modal-body">
                <h4>¿Desea imprimir la facturacion del barrio:$?</h4>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-warning " id="enviar">Si</a>
                <a href="#" class="btn btn-danger" data-dismiss="modal">No</a>
            </div>
        </div>
    </div>
</div>
<script>
                $('#modalEliminarServicio1').on('show.bs.modal', function (event) {
       var button = $(event.relatedTarget)
       var recipent = button.data('id')
       var nom = button.data('nom')
       var modal = $(this);
       modal.find('h4').text('¿Desea imprimir la facturacion del barrio: ' + nom + '?');
       modal.find('#enviar').attr('href', 'generarUNUSUARIOPDF/' + recipent);
   });               
</script>
<?php 
//$html = ob_get_clean();
////echo $html;
//include_once 'dompdf/autoload.inc.php';
////include_once 'fpdf/fpdf.php';
//use Dompdf\Dompdf;
//$dompdf = new Dompdf();
//
//$options = $dompdf->getOptions();
//$options->set(array('isRemoteEnabled'=> true));
//$dompdf->setOptions($options);
//$dompdf->loadHtml($html);
////$dompdf->loadHtml("hola develoteca");
//$dompdf->setPaper('letter');
//
//$dompdf->render();
//
//$dompdf->stream("reportes_morosos.pdf", array("Attachment"=>true));
?>