<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <link rel='icon' href='<?php echo COMMON; ?>img/icono.ico'>
    <a href="../common/img/icono.ico"></a>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><?php echo $this->title; ?></title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="<?php echo COMMON; ?>assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo COMMON; ?>assets/dist/css/adminlte.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- DataTables -->
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>

    <style>
        /* Estilos personalizados para el badge "PAGADA" */
        .badge-pagada {
            background-color: green;
            color: white;
            font-size: 12px;
            padding: 2px 5px;
            border-radius: 3px;
        }
        .badge-Suspendido {
            background-color: red;
            color: white;
            font-size: 12px;
            padding: 2px 5px;
            border-radius: 3px;
        }
    </style>
</head>

<body>
    <div>
        <table style="width: 100%;" class="table table-bordered table-hover tab-custom-content table-borderless table-sm table-condensed table-centered dataTable" id="DataTable" width="100%" cellspacing="0">
            <thead>
                <tr> 
                    <th class="col-sm-">NIT</th>
                    <th class="col-sm-">NOMBRES & APELLIDOS</th>
                    <th class="col-sm-">DIRECCION</th>
                    <th class="col-sm-">CTO</th>
                    <th class="col-sm-">FECHA/INICIO</th>   
                    <th class="col-sm-">N/FACT</th>
                    <th class="col-sm-">DEUDA</th>   
                    <th class="col-sm-">OPCION</th>   
                </tr>
            </thead>
            <tbody class="table-condensed">
                <?php
                for ($i = 0; $i < count($this->datos); $i++) {
                    ?>
                    <tr >
                        <td class="text-center" ><?php echo ucwords(strtolower($this->datos[$i]['uosDocumento'])); ?></td>
                        <td class="text-center" ><?php echo ucwords(strtolower($this->datos[$i]['NOMBRES'])); ?></td>
                        <td class="text-center" ><?php echo ucwords(strtolower($this->datos[$i]['DIRECCION'])); ?></td>
                        <td class="text-center" ><?php echo ucwords(strtolower($this->datos[$i]['froContrato'])); ?>
                        <?php if ($this->datos[$i]['cosEstado'] == 'SUSPENDIDO') { ?>
                                <span class="badge badge-Suspendido">Suspendido</span>
                            <?php } ?>
                        </td>
                        
                        <td class="text-center" ><?php echo ucwords(strtolower($this->datos[$i]['cosFechainici'])); ?> </td>
                        <td class="text-center b" ><?php echo ucwords(strtolower($this->datos[$i]['froNomFctura'])); ?> 

                            <?php if ($this->datos[$i]['froEstadoFactura'] == 'PAGADA') { ?>
                                <span class="badge badge-pagada">PAGADA</span>
                            <?php } ?>
                        </td>
                        <?php
                        $valor = $this->datos[$i]['froTotalVenta'];
                        $formato = number_format($valor, 2);
                        ?>
                        <td class="text-center" ><?php echo '$ ', $formato; ?></td>
                        <td class="text-center">
                            <?php if ($this->datos[$i]['cosEstado'] == 'SUSPENDIDO') { ?>
                                <span class="badge badge-Suspendido">Suspendido</span>
                            <?php }else{ ?>
                            <button
                                id="btncortar"
                                title="Suspender"
                                class="default btn-info btn-sm-custom" 
                                value="<?php echo $this->datos[$i]['froNomFctura']; ?>"
                                data-id="<?php echo $this->datos[$i]['froNomFctura']; ?>" 
                                data-nom="<?php echo ucwords(strtolower($this->datos[$i]['froNomFctura'])); ?>">
                                <i class="fa fa-scissors fa-sm"><span> Suspender</span></i> 
                            </button>
                            <?php    } ?>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </div>

    <script>
        $(document).ready(function () {
            $('#DataTable').DataTable();
        });
    </script>
</body>

</html>
