<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.5/css/bootstrap-select.min.css" />
<link rel="stylesheet" href="style.css" />
<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.5/js/bootstrap-select.min.js"></script>
<style type="text/css" media="screen">
    <!--
    .abs-center {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 2vh;
    }

    .for {
        width: 450px;
    }
    -->
</style>
<link href="<?php echo COMMON; ?>/sweetalert.css" rel="stylesheet" type="text/css"/>
<script src="<?php echo COMMON; ?>/sweetalert.min.js" type="text/javascript"></script>
<script src='<?php echo COMMON; ?>js/validar.js'></script>

<script src="<?php echo COMMON; ?>/js/ajax.js" type="text/javascript"></script>
<script src="<?php echo COMMON; ?>/js/jquery.js" type="text/javascript"></script>
<script src='<?php echo COMMON; ?>js/validar.js'></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

<div id="divcarga">
    <form id="form1" method="post" enctype="multipart/form-data" action="<?php echo RUTA_URL . 'facturacion/GuardarUnicaFactura'; ?>">

        <div class="card-body container">

            <div class="form-group">
                <fieldset>
                    <div class="container-fluid card">
                        <div class="row ">
                            <div class="container-fluid card-header bg-lightblue border-success"> 
                                <h5 class="text-center "><?php echo $this->accion; ?></h5>
                            </div>  </div>

                    </div>
                    <STYLE type="text/css">
                        H4 { text-align: center}
                    </STYLE>
            </div>
            <?PHP
            $now = new DateTime();
            $dia = $now->format('n');

            if ($dia < 10) {
                $dia1 = $now->format('n');
                $año = $now->format('Y');
                $TOTAL = $año . '-' . '0' . $dia1;
            } else {
                $dia1 = $now->format('n');
                $año = $now->format('Y');
                $TOTAL = $año . '-' . $dia1;
            }
            ?>
            <div class="container card-body card">
                <div class="col-12 col-md-12 d-flex justify-content-center align-items-center">
                    <div class="col-md-3 text-right">
                        <label for="cliente_numero_documento" class="bmd-label-floating">Seleciona Periodo:&nbsp;</label>
                    </div>
                    <div class="col-md-6">
                        <select class="custom-select w-100 col-md-8" id="txtPeriodo" name="txtPeriodo">
                            <option>Seleccionar Periodo</option>
                            <?php
                            $ultimaOpcionA = null;
                            for ($i = 0; $i < count($this->ConsultaPeriodosFacturados); $i++) {
                                if ($this->ConsultaPeriodosFacturados[$i]['perEstado'] == 'a') {
                                    $ultimaOpcionA = $this->ConsultaPeriodosFacturados[$i];
                                }
                            }

                            for ($i = 0; $i < count($this->ConsultaPeriodosFacturados); $i++) {
                                if ($this->ConsultaPeriodosFacturados[$i]['perEstado'] == 'a') {
                                    if ($this->ConsultaPeriodosFacturados[$i]['perId'] == $ultimaOpcionA['perId']) {
                                        // Última opción 'a', se habilita la opción
                                        ?>
                                        <option value="<?php echo $this->ConsultaPeriodosFacturados[$i]['perId'] ?>"><?php echo $this->ConsultaPeriodosFacturados[$i]['perMes'] ?></option>
                                        <?php
                                    } else {
                                        // Opciones anteriores 'a', se deshabilita la opción
                                        ?>
                                        <option disabled="disabled" class="alert alert-danger" value="<?php echo $this->ConsultaPeriodosFacturados[$i]['perId'] ?>"><?php echo $this->ConsultaPeriodosFacturados[$i]['perMes'] ?></option>
                                        <?php
                                    }
                                } else {
                                    // Otros periodos, se habilita la opción
                                    ?>
                                    <option class="alert alert-default-info" value="<?php echo $this->ConsultaPeriodosFacturados[$i]['perId'] ?>"><?php echo $this->ConsultaPeriodosFacturados[$i]['perMes'] ?></option>
                                    <?php
                                }
                            }
                            ?>
                        </select>

                        <span class="input-group-text"><?php echo $año; ?></span>
                    </div>

                </div>
                <br><!--    <br> -->
                <div class="col-12 col-md-12 row ">
                    <div class="col-md-12 d-flex justify-content-center">
                        <label for="cliente_numero_documento" class="bmd-label-floating col-md-3 text-right">Numero de Factura:&nbsp;</label>
                        <?php
                        $num = $this->contultafactura[0]['froNomFctura'];
                        $num++
                        ?>
                        <input type="hidden" id="txtsosId" name="txtsosId" value="<?php echo $num; ?>">
                        <input value="<?php echo $num; ?>" type="text" class="form-control col-md-3" name="NumFactura" id="NumFactura" placeholder="Num Factura" readonly>
                        <label for="cliente_numero_documento" class="bmd-label-floating col-md-3 text-right">Fecha de Elaboracion:&nbsp;</label>
                        <input type="date" class="form-control col-md-3" name="dateFechaElaboracion" id="dateFechaElaboracion" placeholder="Fecha Elaboracion" readonly>

                    </div>


                    <script>
                        // Obtener el campo de entrada de fecha
                        var fechaElaboracionInput = document.getElementById('dateFechaElaboracion');

                        // Obtener la fecha actual
                        var fechaActual = new Date();

                        // Convertir la fecha actual a formato ISO (YYYY-MM-DD)
                        var fechaActualISO = fechaActual.toISOString().split('T')[0];

                        // Establecer la fecha actual como el valor predeterminado del campo de entrada de fecha
                        fechaElaboracionInput.value = fechaActualISO;
                    </script>
                    <br/><br/>
                    <div class="col-md-12 row">
                        <label for="cliente_numero_documento" class="bmd-label-floating col-md-2 text-right">Consulta Usuario:&nbsp;</label>
                        <div class="form-inline col-md-10">
                            <select id="cmDocumento" name="cmDocumento" class="selectpicker col-9" data-show-subtext="true" data-live-search="true">
                                <option class="" value="0000">Seleccione datos</option>
                                <?php for ($i = 0; $i < count($this->consultaselec); $i++) { ?> 
                                    <option   value="<?php echo $this->consultaselec[$i]['uosDocumento'] ?>" class="text-capitalize" data-subtext=" <?php
                                    echo $this->consultaselec[$i]['NOMBRES'];
                                    ?>"><?php echo $this->consultaselec[$i]['uosDocumento'] ?> </option>
                                          <?php } ?>
                            </select>
                            <button type="button" id="btncontultausuario" class="btn btn-primary col-md-2">Consultar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div id="divcargadatosusuario">


            </div>


            
        </div>
    </form>
    
</div>
<div role="navigation" class="navbar navbar-inverse navbar-static-top">
</div>      


