<?php

//include_once './fpdf/fpdf.php';
require 'fpdf/fpdf.php';
$fpdf = new FPDF();
$fpdf->AddPage(); //SE CREA UNA PAGINA
///ENCABEZADO


/*
 * author: Código Root </>
 * Mi blog: https://codigoroot.net/blog
 */

class pdf extends FPDF {

    public function Header() {
        $this->SetMargins(5, 10, 0, 10);
        $this->SetFont('Courier', 'B', 12);
        date_default_timezone_set('America/Lima');
        $fechaActual_1 = date('y-m-d h:i:s');
        $this->Cell(0, 5, 'Fecha de Reporte ' . $fechaActual_1, 0, 0, '');
        $this->Image(COMMON . 'img/logoversion3.png', 170, 5, 35, 20, 'png');
        $this->Ln();
        $this->Ln();
        $this->SetFont('arial', 'BU', 15);
        $this->SetTextColor(16, 87, 97);
        $this->Cell(0, 5, "REPORTE DE USUARIOS CON SALDOS", 0, 0, 'C');
        $this->Ln();
        $this->Ln();
        $this->SetFont('arial', 'B', 9);
        $this->SetFillColor(55, 89, 78);
        $this->Cell(23, 5, 'NIT', 1, 0, 'C', FALSE);
        $this->Cell(45, 5, 'NOMBRES & APELLIDOS', 1, 0, 'C', FALSE);
        $this->Cell(45, 5, 'DIRECCION', 1, 0, 'C', FALSE);
        $this->Cell(10, 5, 'CTO', 1, 0, 'C', FALSE);
        $this->Cell(23, 5, 'ESTADO CTO', 1, 0, 'C', FALSE);
        $this->Cell(15, 5, 'No.FAC', 1, 0, 'C', FALSE);
        $this->Cell(20, 5, 'FECHA', 1, 0, 'C', FALSE);
        $this->Cell(23, 5, 'VALOR', 1, 0, 'C', FALSE);
//        $this->Cell(25, 5, 'FECHA FINAL', 1, 0, 'C', FALSE);
        $this->Ln();
    }

    public function Footer() {

        $this->SetFont('Courier', 'B', 12);
        $this->SetY(-15);
        $this->Write(5, 'CableTvColombia');
        $this->SetX(-32);
        $this->AliasNbPages();
        $this->Write(5, $this->PageNo() . '/{nb}');
    }

}

//$fpdf->SetFont('Arial', 'BU', 15);
//$fpdf->SetY(30);
//$fpdf->SetTextColor(16, 87, 97);
//$fpdf->Cell(0, 5, "LISTADO USUARIOS MOROSOS", 0, 0, 'C'); //ANCHO, ALTO, (EN CENTIMETROS)
//$fpdf->SetTextColor(0, 0, 0);
$fpdf = new pdf('P', 'mm', 'letter', true);
for ($e = 0; $e < count($this->datosbarrio); $e++) {
    $fpdf->AddPage('portrait', 'letter');
    $fpdf->SetMargins(5, 10, 0, 10);
    $barrio = $this->datosbarrio[$e]['banombre'];
    $valordeuno = 0;
    $CONTARUSUARIO = 0;
    for ($i = 0; $i < count($this->datos); $i++) {

        $Idcontrato1 = $this->datos[$i]['cosId'];

        $barrio2 = $this->datos[$i]['banombre'];
        if ($barrio == $barrio2) {

            $fpdf->SetFont('arial', '', 9);
            $fpdf->Cell(23, 5, utf8_decode($this->datos[$i]['uosDocumento']), 1, 0, 'C', FALSE);
            $fpdf->Cell(45, 5, utf8_decode(ucwords(strtolower($this->datos[$i]['NOMBRES']))), 1, 0, '', FALSE);
            $fpdf->Cell(45, 5, utf8_decode(ucwords(strtolower($this->datos[$i]['DIRECCION']))), 1, 0, '', FALSE);
            $fpdf->Cell(10, 5, utf8_decode($this->datos[$i]['cosId']), 1, 0, '', FALSE);
            $estado = $this->datos[$i]['cosEstado'];
            if ($estado == 'SUSPENDIDO') {
                $fpdf->SetFillColor(255, 204, 204); // Establecer color de fondo para la fila suspendida
                $fpdf->Cell(23, 5, utf8_decode($this->datos[$i]['cosEstado']), 1, 0, '', TRUE);
            } else {
                $fpdf->SetFillColor(255, 255, 255); // Restablecer el color de fondo predeterminado para las otras filas
                $fpdf->Cell(23, 5, utf8_decode($this->datos[$i]['cosEstado']), 1, 0, '', TRUE);
            }


            for ($y = 0; $y < count($this->datosfacturamaestro); $y++) {
                $IdContrato2 = $this->datosfacturamaestro[$y]['froContrato'];
                if ($IdContrato2 == $Idcontrato1) {
                    $estadoFAC = $this->datosfacturamaestro[$y]['froEstadoFactura'];


                    if ($estadoFAC == 'PAGADA' or $estadoFAC == 'PAGADASUSPENDIDO') {
                        $fpdf->SetFillColor(204, 255, 204); // Establecer color de fondo para la fila pagada
                        $fpdf->Cell(15, 5, utf8_decode($this->datosfacturamaestro[$y]['froNomFctura']), 1, 0, '', TRUE);
                        $fpdf->Cell(20, 5, utf8_decode($this->datosfacturamaestro[$y]['froFecha']), 1, 0, '', TRUE);
                        $valor = $this->datosfacturamaestro[$y]['froTotalVenta'];
                        $formato = number_format($valor, 2);
                        $fpdf->Cell(23, 5, '$' . $formato, 1, 0, '', TRUE);
                    }
                    if ($estadoFAC == 'PORPAGAR') {
                        $fpdf->SetFillColor(255, 255, 153); // Establecer color de fondo para la fila pagada
                        $fpdf->Cell(15, 5, utf8_decode($this->datosfacturamaestro[$y]['froNomFctura']), 1, 0, '', TRUE);
                        $fpdf->Cell(20, 5, utf8_decode($this->datosfacturamaestro[$y]['froFecha']), 1, 0, '', TRUE);
                        $valor = $this->datosfacturamaestro[$y]['froTotalVenta'];
                        $formato = number_format($valor, 2);
                        $fpdf->Cell(23, 5, '$' . $formato, 1, 0, '', TRUE);
                    }
                    if ($estadoFAC == 'SUSPENDIDO') {
                        $fpdf->SetFillColor(255, 204, 204); // Establecer color de fondo para la fila pagada
                        $fpdf->Cell(15, 5, utf8_decode($this->datosfacturamaestro[$y]['froNomFctura']), 1, 0, '', TRUE);
                        $fpdf->Cell(20, 5, utf8_decode($this->datosfacturamaestro[$y]['froFecha']), 1, 0, '', TRUE);
                        $valor = $this->datosfacturamaestro[$y]['froTotalVenta'];
                        $formato = number_format($valor, 2);
                        $fpdf->Cell(23, 5, '$' . $formato, 1, 0, '', TRUE);
                    }
                    
                }
            }

//            $fpdf->Cell(25, 5, utf8_decode($this->datos[$i]['cosFechafinal']), 1, 0, '', FALSE);


            $fpdf->Ln();


            $CONTARUSUARIO += 1;
            $valordeuno += 1;
        }
    }
    $fpdf->SetTextColor(243, 12, 43);
    $fpdf->Cell(204, 20, utf8_decode('Total de usuarios registrados en el barrio ' . $barrio . ': ' . $CONTARUSUARIO), 1, 'B', 'C', FALSE);
    $fpdf->SetTextColor(0, 0, 0);
    $CONTARUSUARIO = 0;
    if ($valordeuno == '0') {
        $fpdf->SetTextColor(243, 12, 43);
        $fpdf->Cell(204, 20, utf8_decode('NO HAY USUARIOS PARA EL BARRIO: ' . $barrio), 1, 'B', 'C', FALSE);
        $fpdf->SetTextColor(0, 0, 0);
    }
    $fpdf->Ln();
    
    $fpdf->SetFont('Arial', 'B', 10); // Establecer fuente, estilo y tamaño
    $fpdf->Cell(65, 8, 'GUIA DE COLORES', 1, 0, 'C', false); // Celda combinada con color de fondo
    $fpdf->Ln(); // Salto de línea después del título
// Primera fila: PAGADA y color verde claro
    $fpdf->Cell(50, 8, 'PAGADA', 1, 0, 'C');
    $fpdf->SetFillColor(204, 255, 204); // Establecer color de fondo para la celda
    $fpdf->Cell(15, 8, '', 1, 0, '', true);

// Segunda fila: POR PAGAR y color amarillo claro
    $fpdf->Ln(); // Salto de línea para la siguiente fila
    $fpdf->Cell(50, 8, 'POR PAGAR', 1, 0, 'C');
    $fpdf->SetFillColor(255, 255, 204); // Establecer color de fondo para la celda
    $fpdf->Cell(15, 8, '', 1, 0, '', true);

// Tercera fila: SUSPENDIDO y color rojo claro
    $fpdf->Ln(); // Salto de línea para la siguiente fila
    $fpdf->Cell(50, 8, 'SUSPENDIDO SIN PAGAR', 1, 0, 'C');
    $fpdf->SetFillColor(255, 204, 204); // Establecer color de fondo para la celda
    $fpdf->Cell(15, 8, '', 1, 0, '', true);
}



// SE CREA OTRA PAGINA 
$fpdf->Output('I', 'NOMBREARCHIVO.PDF'); //recibe el parametro I<Se muestra en el navegador, D-descargar, f-guarda delntro del servidor
?>