<?php

//include_once './fpdf/fpdf.php';
require 'fpdf/fpdf.php';
$fpdf = new FPDF();
$fpdf->AddPage(); //SE CREA UNA PAGINA
///ENCABEZADO


/*
 * author: Código Root </>
 * Mi blog: https://codigoroot.net/blog
 */

class pdf extends FPDF {

    public function Header() {
        $this->SetFont('Courier', 'B', 12);
        date_default_timezone_set('America/Lima');
        $fechaActual_1 = date('y-m-d h:i:s');
        $this->Cell(0, 5, 'Fecha de Reporte ' . $fechaActual_1, 0, 0, '');
        $this->Image(COMMON . 'img/logoversion3.png', 170, 5, 35, 20, 'png');
        $this->Ln();
        $this->Ln();
        $this->SetFont('arial', 'BU', 15);
        $this->SetTextColor(16, 87, 97);
        $this->Cell(0, 5, "REPORTE DE USUARIOS", 0, 0, 'C');
        $this->Ln();
        $this->Ln();
        $this->SetFont('arial', 'B', 9);
        $this->SetFillColor(55, 89, 78);
        $this->Cell(23, 5, 'NIT', 1, 0, 'C', FALSE);
        $this->Cell(50, 5, 'NOMBRES & APELLIDOS', 1, 0, 'C', FALSE);
        $this->Cell(50, 5, 'DIRECCION', 1, 0, 'C', FALSE);
        $this->Cell(10, 5, 'CTO', 1, 0, 'C', FALSE);
        $this->Cell(30, 5, 'ESTADO CTO', 1, 0, 'C', FALSE);
        $this->Cell(32, 5, 'FECHA INICIO', 1, 0, 'C', FALSE);
//        $this->Cell(25, 5, 'FECHA FINAL', 1, 0, 'C', FALSE);
        $this->Ln();
    }

    public function Footer() {

        $this->SetFont('Courier', 'B', 12);
        $this->SetY(-15);
        $this->Write(5, 'CableTvColombia');
        $this->SetX(-32);
        $this->AliasNbPages();
        $this->Write(5, $this->PageNo() . '/{nb}');
    }

}

//$fpdf->SetFont('Arial', 'BU', 15);
//$fpdf->SetY(30);
//$fpdf->SetTextColor(16, 87, 97);
//$fpdf->Cell(0, 5, "LISTADO USUARIOS MOROSOS", 0, 0, 'C'); //ANCHO, ALTO, (EN CENTIMETROS)
//$fpdf->SetTextColor(0, 0, 0);

$fpdf = new pdf('P', 'mm', 'letter', true);
for ($e = 0; $e < count($this->datosbarrio); $e++) {
    $fpdf->AddPage('portrait', 'letter');
    $fpdf->SetMargins(10, 10, 10, 10);
    $barrio = $this->datosbarrio[$e]['banombre'];
    $valordeuno = 0;
   $CONTARUSUARIO = 0;
    for ($i = 0; $i < count($this->datos); $i++) {
        
        $barrio2 = $this->datos[$i]['banombre'];
        if ($barrio == $barrio2) {

            $fpdf->SetFont('arial', '', 9);
            $fpdf->Cell(23, 5, utf8_decode($this->datos[$i]['uosDocumento']), 1, 0, 'C', FALSE);
            $fpdf->Cell(50, 5, utf8_decode(ucwords(strtolower($this->datos[$i]['NOMBRES']))), 1, 0, '', FALSE);
            $fpdf->Cell(50, 5, utf8_decode(ucwords(strtolower($this->datos[$i]['DIRECCION']))), 1, 0, '', FALSE);
            $fpdf->Cell(10, 5, utf8_decode($this->datos[$i]['cosId']), 1, 0, '', FALSE);
            $fpdf->Cell(30, 5, utf8_decode($this->datos[$i]['cosEstado']), 1, 0, '', FALSE);
            $fpdf->Cell(32, 5, utf8_decode($this->datos[$i]['cosFechainici']), 1, 0, '', FALSE);

//            $fpdf->Cell(25, 5, utf8_decode($this->datos[$i]['cosFechafinal']), 1, 0, '', FALSE);
            $fpdf->Ln();


            $CONTARUSUARIO += 1;
            $valordeuno += 1;
        }
    }
    $fpdf->SetTextColor(243, 12, 43);
    $fpdf->Cell(195, 20, utf8_decode('Total de usuarios registrados en el barrio '.$barrio.': ' . $CONTARUSUARIO), 1, 'B', 'C', FALSE);
    $fpdf->SetTextColor(0, 0, 0);
    $CONTARUSUARIO = 0;
    if ($valordeuno == '0') {
        $fpdf->SetTextColor(243, 12, 43);
        $fpdf->Cell(198, 20, utf8_decode('NO HAY USUARIOS PARA EL BARRIO: ' . $barrio), 1, 'B', 'C', FALSE);
        $fpdf->SetTextColor(0, 0, 0);
    }
}

// SE CREA OTRA PAGINA 
$fpdf->Output('I', 'NOMBREARCHIVO.PDF'); //recibe el parametro I<Se muestra en el navegador, D-descargar, f-guarda delntro del servidor
?>