<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js">

</script>

<!-- comment --><div class="content">

    <div class="container-fluid">

        <!-- row Tarjetas Informativas -->
        <div class="container-fluid row">

            <div class="col-lg-2">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h4 id="totalCompras"><?php
                            $valor = $this->CAJAGENERAL[0]['tasValor'];
                            $formato = number_format($valor, 2);

                            echo '$/' . $formato;
                            ?>

                        </h4>
                        <p>Caja General</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-clipboard"></i>
                    </div>
                    <a style="cursor:pointer;" class="small-box-footer" href= "<?php echo RUTA_URL; ?>reportes/iniciomorosos">Mas Info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

            <!-- TARJETA TOTAL COMPRAS -->
            <div class="col-lg-2">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h4 id="totalCompras"> <?php
                            $valor = $this->CAJAMES[0]['TOTAL'];
                            $formato = number_format($valor, 2);
                            echo '$/' . $formato;
                            ?></h4>

                        <p>Total Recaudos Mes</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-cash"></i>
                    </div>
                    <a style="cursor:pointer;" class="small-box-footer" href= "<?php echo RUTA_URL; ?>facturacion/pagos">Mas Info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

            <!-- TARJETA TOTAL VENTAS -->
            <div class="col-lg-2">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h4 id="totalVentas">N° 
                            <?php
                            echo $this->datosMoroso[0]['MOROSOS'];
                            ?>
                        </h4>
                        <p>Usuarios Morosos Mes</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-cart"></i>
                    </div>
                    <a style="cursor:pointer;" class="small-box-footer" href= "<?php echo RUTA_URL; ?>reportes/iniciomorosos">Mas Info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

            <!-- TARJETA TOTAL GANANCIAS -->
            <div class="col-lg-2">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h4 id="totalGanancias"> N°  
                            <?php
                            echo $this->datosSuspendidos[0]['SUPENDIDOS'];
                            ?></h4>

                        <p>Total Usuarios Suspendidos</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-pie"></i>
                    </div>
                    <a style="cursor:pointer;" class="small-box-footer" href= "<?php echo RUTA_URL; ?>reportes/iniciosuspendidos">Mas Info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

            <!-- TARJETA PRODUCTOS POCO STOCK -->
            <div class="col-lg-2">
                <!-- small box -->
                <div class="small-box bg-primary">
                    <div class="inner">
                        <h4 id="totalGanancias"> N°  
                            <?php
                           echo $this->datosActivos[0]['total'];
                            ?></h4>

                        <p>Usuarios Activos</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-android-remove-circle"></i>
                    </div>
                    <a style="cursor:pointer;" class="small-box-footer" href= "<?php echo RUTA_URL; ?>humanos/inicioclientes">Mas Info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>

            <!-- TARJETA TOTAL VENTAS DIA ACTUAL -->
            <div class="col-lg-2">
                <!-- small box -->
                <div class="small-box bg-secondary">
                    <div class="inner">
                        <h4 id="totalVentasHoy"> <?php
                           echo $this->ordenespendiente[0]['total'];
                            ?></h4>

                        <p>Ordenes Pendientes</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-android-calendar"></i>
                    </div>
                    <a style="cursor:pointer;" class="small-box-footer" href= "<?php echo RUTA_URL; ?>ordenes/ordenes">Mas Info <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>




            <!-- ./row Tarjetas Informativas -->



        </div>
        <br>
        <style type="text/css">
            #grafica { height: 500x; 
                       width: 1000px; }
            </style>
        </div>
    </div>
    <div id="divgrafica" class="row">

    <div id="divgrafica"  class="text-center">     <?php
        $enero2 = 0;
        $febrero2 = 0;
        $marzo2 = 0;
        $abril2 = 0;
        $mayo2 = 0;
        $junio2 = 0;
        $julio2 = 0;
        $agosto2 = 0;
        $septiembre2 = 0;
        $octubre2 = 0;
        $noviembre2 = 0;
        $diciembre2 = 0;
        for ($i = 0; $i < count($this->datospagos2); $i++) {
            if ($this->datospagos2[$i]['perMes'] == 'enero') {
                $enero2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'febrero') {
                $febrero2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'marzo') {
                $marzo2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'abril') {
                $abril2 = $this->datospagos2[$i]['froTotalVenta'];
            } if ($this->datospagos2[$i]['perMes'] == 'mayo') {
                $mayo2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'junio') {
                $junio2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'julio') {
                $julio2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'agosto') {
                $agosto2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'septiembre') {
                $septiembre2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'octubre') {
                $octubre2 = $this->datospagos2[$i]['froTotalVenta'];
            }if ($this->datospagos2[$i]['perMes'] == 'noviembre') {
                $noviembre2 = $this->datospagos2[$i]['froTotalVenta'];
            } if ($this->datospagos2[$i]['perMes'] == 'diciembre') {
                $diciembre2 = $this->datospagos2[$i]['froTotalVenta'];
            }
        }
        $enero = 0;
        $febrero = 0;
        $marzo = 0;
        $abril = 0;
        $mayo = 0;
        $junio = 0;
        $julio = 0;
        $agosto = 0;
        $septiembre = 0;
        $octubre = 0;
        $noviembre = 0;
        $diciembre = 0;
        for ($i = 0; $i < count($this->datospagos); $i++) {


            if ($this->datospagos[$i]['perMes'] == 'enero') {
                $enero = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'febrero') {
                $febrero = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'marzo') {
                $marzo = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'abril') {
                $abril = $this->datospagos[$i]['froTotalVenta'];
            } if ($this->datospagos[$i]['perMes'] == 'mayo') {
                $mayo = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'junio') {
                $junio = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'julio') {
                $julio = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'agosto') {
                $agosto = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'septiembre') {
                $septiembre = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'octubre') {
                $octubre = $this->datospagos[$i]['froTotalVenta'];
            }if ($this->datospagos[$i]['perMes'] == 'noviembre') {
                $noviembre = $this->datospagos[$i]['froTotalVenta'];
            } if ($this->datospagos[$i]['perMes'] == 'diciembre') {
                $diciembre = $this->datospagos[$i]['froTotalVenta'];
            }
        }
        $enero1 = 0;
        $febrero1 = 0;
        $marzo1 = 0;
        $abril1 = 0;
        $mayo1 = 0;
        $junio1 = 0;
        $julio1 = 0;
        $agosto1 = 0;
        $septiembre1 = 0;
        $octubre1 = 0;
        $noviembre1 = 0;
        $diciembre1 = 0;
        for ($i = 0; $i < count($this->datospagos1); $i++) {


            if ($this->datospagos[$i]['perMes'] == 'enero') {
                $enero1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'febrero') {
                $febrero1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'marzo') {
                $marzo1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'abril') {
                $abril1 = $this->datospagos1[$i]['froTotalVenta'];
            } if ($this->datospagos1[$i]['perMes'] == 'mayo') {
                $mayo1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'junio') {
                $junio1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'julio') {
                $julio1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'agosto') {
                $agosto1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'septiembre') {
                $septiembre1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'octubre') {
                $octubre1 = $this->datospagos1[$i]['froTotalVenta'];
            }if ($this->datospagos1[$i]['perMes'] == 'noviembre') {
                $noviembre1 = $this->datospagos1[$i]['froTotalVenta'];
            } if ($this->datospagos1[$i]['perMes'] == 'diciembre') {
                $diciembre1 = $this->datospagos1[$i]['froTotalVenta'];
            }
        }


// Valores con PHP. Estos podrían venir de una base de datos o de cualquier lugar del servidor
        $etiquetas = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"];
        $datosVentas = [$enero, $febrero, $marzo, $abril, $mayo, $junio, $julio, $agosto, $septiembre, $octubre, $noviembre, $diciembre];
        $datosVentas1 = [$enero1, $febrero1, $marzo1, $abril1, $mayo1, $junio1, $julio1, $agosto1, $septiembre1, $octubre1, $noviembre1, $diciembre1];

        $datosVentas2 = [$enero2, $febrero2, $marzo2, $abril2, $mayo2, $junio2, $julio2, $agosto2, $septiembre2, $octubre2, $noviembre2, $diciembre2];
        ?>

        <h2>Reporte Grafico Facturacion</h2>

        <canvas id="grafica"></canvas>
        <script type="text/javascript">
            // Obtener una referencia al elemento canvas del DOM
            const $grafica = document.querySelector("#grafica");
            // Pasaamos las etiquetas desde PHP
            const etiquetas = <?php echo json_encode($etiquetas) ?>;
            // Podemos tener varios conjuntos de datos. Comencemos con uno
            const datosVentas2020 = {
                label: "Facturas Pagas",
                // Pasar los datos igualmente desde PHP
                data: <?php echo json_encode($datosVentas) ?>,
                backgroundColor: 'rgba(54, 162, 235, 0.2)', // Color de fondo
                borderColor: 'rgba(54, 162, 235, 1)', // Color del borde
                borderWidth: 1, // Ancho del borde
            };
            const datosVentas2022 = {
                label: "Facturas vencidas",
                // Pasar los datos igualmente desde PHP
                data: <?php echo json_encode($datosVentas1) ?>,
                backgroundColor: 'rgba(	240, 157, 100, 0.2)', // Color de fondo
                borderColor: 'rgba(240, 157, 100, 1)', // Color del borde
                borderWidth: 1, // Ancho del borde
            };
            const datosVentas2023 = {
                label: "Facturas Por Pagar",
                // Pasar los datos igualmente desde PHP
                data: <?php echo json_encode($datosVentas2) ?>,
                backgroundColor: 'rgba(100, 240, 157, 0.2)', // Color de fondo
                borderColor: 'rgba(100, 240, 1570, 1)', // Color del borde
                borderWidth: 1, // Ancho del borde
            };
            new Chart($grafica, {
                type: 'line', // Tipo de gráfica
                data: {
                    labels: etiquetas,
                    datasets: [
                        datosVentas2020,
                         datosVentas2022,
                         datosVentas2023,
                        // Aquí más datos...
                    ]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }],
                    },
                }
            });
        </script>
    </div>

    <div>
        <h2>Reporte Grafico Usuarios</h2>
        <div style="width: 500px">
            <canvas id="grafica1"></canvas>
        </div>
        <script type="text/javascript">
            
      const labels = ['Total',  'Activos','Suspendidos', 'Por Definir']
const colors = ['rgb(69,177,223)',  'rgb(99,201,122)','rgb(203,82,82)', 'rgb(229,224,88)'];

const graph = document.querySelector("#grafica1");

const data = {
    labels: labels,
    datasets: [{
        data: [<?php
        echo $this->datostotal[0]['total'];
        ?>,<?php
        echo $this->datosActivos[0]['total'];
        ?>, <?php
        echo $this->datosSuspendidos[0]['SUPENDIDOS'];
        ?>,  <?php
        echo $this->datosPendiente[0]['total'];
        ?>],
        backgroundColor: colors
    }]
};

const config = {
    type: 'pie',
    data: data,
};

new Chart(graph, config);
        </script>
<?php ?>
    </div>

</div>




