<?php declare(strict_types=1) ?>
<!DOCTYPE html>
<html lang="en">

    <head>
       
        <meta charset="utf-8">
        <link rel='icon' href='<?php echo COMMON; ?>img/icono.ico'>
    <a href="../common/img/icono.ico"></a>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><?php echo $this->title; ?></title>
    <!--!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" > 
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="<?php echo COMMON; ?>assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo COMMON; ?>assets/dist/css/adminlte.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- jQuery -->
    <script src="<?php echo COMMON; ?>assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="<?php echo COMMON; ?>assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="<?php echo COMMON; ?>/datatables/media/js/jquery.dataTables.js" type="text/javascript"></script>
    <link href="<?php echo COMMON; ?>/datatables/media/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo COMMON; ?>/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet" type="text/css"/>
    <script src="<?php echo COMMON; ?>/datatables/extensions/Responsive/js/dataTables.responsive.js" type="text/javascript"></script>
    <link href="<?php echo COMMON ?>/datatables/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" type="text/css"/>
    <script src="<?php echo COMMON; ?>assets/dist/js/adminlte.min.js"></script>
    <script src="<?php echo COMMON; ?>js/jquery.js"></script>
    <link href="<?php echo COMMON; ?>vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo COMMON; ?>vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="<?php echo COMMON; ?>vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="<?php echo COMMON; ?>css/sb-admin.css" rel="stylesheet">
    <link href="<?php echo COMMON; ?>css/pnotify.custom.min.css" rel="stylesheet">
    <link href='<?php echo COMMON; ?>formvalidation/dist/css/bootstrapValidator.css' rel='stylesheet'><script src='<?php echo COMMON; ?>formvalidation/dist/js/bootstrapValidator.js'></script><script src='<?php echo COMMON; ?>formvalidation/dist/js/language/es_CL.js'></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7359767203541632"
     crossorigin="anonymous"></script>
</head>

<body class=""hold-transition sidebar-mini"" id="page-top">
    <div class="wrapper">
        <?php if (Session::get('autenticado')) { ?>
            <!-- Navigation-->
            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                    </li>

                </ul>

                <ul class="navbar-nav ml-auto">
                    <li class="dropdown navbar-nav ml-auto " style="">

                        <a  class="dropdown-toggle nav-item  nav-link" data-toggle="dropdown">
                            <i class="fa fa-user-circle-o">
                            </i> <?php echo Session::get('usuario'); ?> 
                        </a>

                        <ul class="dropdown-menu  ">
                            <li class="nav-item"> 
                                <a  href="<?php echo RUTA_URL . 'inicio/cerrarsesion'; ?>" class="nav-link">
                                    <i class="fa fa-fw fa-sign-out">
                                    </i>Cambiar Clave
                                </a>
                            </li>
                            <li class="nav-item"> 
                                <a href="<?php echo RUTA_URL . 'inicio/cerrarsesion'; ?>" class="nav-link">
                                    <i class="fa fa-fw fa-sign-out">
                                    </i>Cerrar Sesion
                                </a>
                            </li>
                        </ul>
                    </li> 

                </ul>
            </nav>
            <!--finaliza navbar-->
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!--logo-->
                <a href="<?php echo RUTA_URL . 'administracion/bienvenido'; ?>" class="brand-link center-block">
                    <span class="brand-text font-weight-light ">  <img src="<?php echo COMMON; ?>img/login2.png" height ="90" width="180"alt="alt"/></span>
                </a>
                <div class="sidebar">
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <?php
                            for ($i = 0; $i < count($_layoutParams['menu1']); $i++) {
                                ?>
                                <?php $submenu = $_layoutParams['menu1'][$i]['id']; ?>
                                <?php $tienemenu = $_layoutParams['menu1'][$i]['sub']; ?>

                                <?php if ($tienemenu == "SI") { ?>

                                    <li class="nav-item">
                                        <a href="#" class="nav-link ">
                                            <i class="<?php echo $_layoutParams['menu1'][$i]['icono']; ?>"></i>
                                            <p>
                                                <?php echo $_layoutParams['menu1'][$i]['titulo']; ?>
                                                <i class="right fas fa-angle-left"></i>
                                            </p>
                                        </a>
                                        <ul class="nav nav-treeview">
                                            <?php
                                            for ($e = 0; $e < count($_layoutParams['menu']); $e++) {
                                                ?>
                                                <?php if ($submenu === $_layoutParams['menu'][$e]['sub']) { ?>
                                                    <li class="nav-item">
                                                        <a class="nav-link" href=" <?php echo $_layoutParams['menu'][$e]['enlace']; ?>">
                                                            <i class="<?php echo $_layoutParams['menu'][$e]['icono']; ?>"></i>
                                                            <span class=""><?php echo $_layoutParams['menu'][$e]['titulo']; ?></span>
                                                        </a>
                                                    </li>
                                                <?php } ?>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                <?php } else if ($tienemenu == "NO") {
                                    ?>
                                    <li class="nav-item">
                                        <a class="nav-link" href=" <?php echo $_layoutParams['menu1'][$i]['enlace']; ?>">
                                            <i class="<?php echo $_layoutParams['menu1'][$i]['icono']; ?>"></i>
                                            <span class=""><?php echo $_layoutParams['menu1'][$i]['titulo']; ?></span>
                                        </a>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>

                    </nav>
                </div>
            </aside>
            <script>
      $(".nav-link").on 
            </script>
            <!--            <div class="collapse navbar-collapse" id="navbarResponsive">
            
                            <ul class="navbar-nav sidenav-toggler">
                                <li class="nav-item">
                                    <a class="nav-link text-center" id="sidenavToggler">
                                        <i class="fa fa-fw fa-angle-left"></i>
                                    </a>
                                </li>
                            </ul>
                            <li class="dropdown navbar-nav ml-auto bg-dark" style="">
            
                                <a  class="dropdown-toggle nav-item bg-dark nav-link" data-toggle="dropdown">
                                    <i class="fa fa-user-circle-o">
                                    </i> <?php echo Session::get('usuario'); ?> 
                                </a>
            
                                <ul class="dropdown-menu bg-dark ">
                                    <li class="nav-item"> 
                                        <a  href="<?php echo RUTA_URL . 'inicio/cerrarsesion'; ?>" class="nav-link">
                                            <i class="fa fa-fw fa-sign-out">
                                            </i>Cambiar Clave
                                        </a>
                                    </li>
                                    <li class="nav-item"> 
                                        <a href="<?php echo RUTA_URL . 'inicio/cerrarsesion'; ?>" class="nav-link">
                                            <i class="fa fa-fw fa-sign-out">
                                            </i>Cerrar Sesion
                                        </a>
                                    </li>
                                </ul>
                            </li> 
            
                        </div>
                    </div>-->
            <div class="loader">
                <div class="loader-img"></div>
            </div>
            <div class="content-wrapper">
                <div class="container-fluid">
                    <!-- Breadcrumbs-->
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="#"><?php echo $this->modulo; ?></a>
                        </li>
                        <li class="breadcrumb-item active"><?php echo $this->metodo; ?></li>
                    </ol>
                <?php } ?>
                <?php
                if (Session::get('mensaje') != '') {
                    ?> <div id="mensaje" class="row"> <div class="col-md-4"></div>
                        <div class="col-md-4 alert <?php echo Session::get('tipomensaje'); ?> alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <strong><?php echo Session::get('mensaje'); ?></strong></div>
                        <div class="col-md-4"></div>
                    </div>
                    <?php
                    Session::set('mensaje', '');
                    Session::set('tipomensaje', '');
                }
                ?>
            